#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Vim
# IFS=: read -ra selected < <(
#   rg --color=always --line-number --no-heading --smart-case "${*:-}" |
#     fzf --ansi \
#         --color "hl:-1:underline,hl+:-1:underline:reverse" \
#         --delimiter : \
#         --layout=reverse \
#         --preview 'bat --color=always {1} --highlight-line {2}' \
#         --preview-window 'down,60%,border-bottom,+{2}+3/3,~3'
# )
# RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
# INITIAL_QUERY="${*:-}"
# IFS=: read -ra selected < <(
#   FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
#   fzf --ansi \
#       --disabled --query "$INITIAL_QUERY" \
#       --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
#       --delimiter : \
#       --layout=reverse \
#       --preview 'bat --color=always {1} --highlight-line {2}' \
#       --preview-window 'down,60%,border-bottom,+{2}+3/3,~3'
# )
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
  fzf --ansi \
      --color "hl:-1:underline,hl+:-1:underline:reverse" \
      --disabled --query "$INITIAL_QUERY" \
      --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
      --bind "alt-enter:unbind(change,alt-enter)+change-prompt(2. fzf> )+enable-search+clear-query" \
      --prompt '1. ripgrep> ' \
      --layout=reverse \
      --delimiter : \
      --preview 'bat --color=always {1} --highlight-line {2}' \
      --preview-window 'down,60%,border-bottom,+{2}+3/3,~3'
)
[ -n "${selected[0]}" ] && echo "${selected[0]}" > ${TMPDIR:-/tmp}/rfv-file && echo "${selected[1]}" >> ${TMPDIR:-/tmp}/rfv-file
